# Generated by Django 2.0.7 on 2018-07-30 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('LANGUAGE_CODE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('LANGUAGE_NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('PROJECT_ID', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('START_DATE', models.DateField()),
                ('PROJECT_NO', models.CharField(max_length=15)),
                ('PROJECT_NAME', models.CharField(max_length=30)),
                ('SUMMARY', models.CharField(max_length=255)),
                ('CUSTOMER', models.CharField(max_length=20, null=True)),
                ('CHARGE', models.CharField(max_length=20, null=True)),
                ('REVIEWER', models.CharField(max_length=20, null=True)),
                ('RELEASE_DATE', models.DateField(null=True)),
                ('REMARKS', models.CharField(max_length=255, null=True)),
                ('LANGUAGE_CODE', models.ForeignKey(db_column='LANGUAGE_CODE', on_delete=django.db.models.deletion.PROTECT, to='login.Language')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('PROTYPE_CODE', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('PROTYPE_NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('STATUS_CODE', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('STATUS_NAME', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='PROTYPE_CODE',
            field=models.ForeignKey(db_column='PROTYPE_CODE', on_delete=django.db.models.deletion.PROTECT, to='login.ProjectType'),
        ),
        migrations.AddField(
            model_name='project',
            name='STATUS_CODE',
            field=models.ForeignKey(db_column='STATUS_CODE', on_delete=django.db.models.deletion.PROTECT, to='login.Status'),
        ),
    ]
