# Generated by Django 2.0.7 on 2018-07-30 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('USERID', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('PASSWORD', models.CharField(max_length=50)),
            ],
        ),
    ]
